// 📋 Lead data structure - matches the API response from db.json
export interface Lead {
  id: string;           // UUID string - generated by json-server
  name: string;         // Required - person's full name
  email: string;        // Required - contact email
  company?: string | null;  // Optional - company name (can be null in messy data!)
  title?: string;       // Optional - job title
  phone?: string;       // Optional - phone number
  tags?: string[];      // Optional - array of tags (watch out for empty/null values!)
  notes?: string | null;    // Optional - long text notes (can be null)
  createdAt: string;    // ISO date string - when the lead was created
}

// 💡 Pro tip: Notice how some fields can be null OR undefined
// The mock data has both scenarios, so handle them gracefully!